### ISSUE TITLE
Cloud recordings not loading correctly

### ISSUE THREAD

**Issue by maxwofford** [hackclub/slash-z#189]
<img width="984" alt="Screenshot 2024-01-27 at 15 01 18" src="https://github.com/hackclub/slash-z/assets/5891442/e423f3b1-adb2-480e-8ddd-7d7af891e44c">

**Comment by hazik-khalid** [comment]
Hi can you be more specific with the issue

**Comment by JosiasAurel** [comment]
this should be fixed now

**Comment by maxwofford** [comment]
<img width="462" alt="Screenshot 2024-02-16 at 13 42 52" src="https://github.com/hackclub/slash-z/assets/5891442/182f3fbf-5225-4564-a749-1d3749a1a2ec">

I'm still getting this!
